#!/bin/sh

CURRENT_VERSION_ID=`cat /etc/os-release |grep VERSION_ID |sed 's/.*=\(.*\)/\1/g'`
NEW_VERSION_ID=`bc <<<"${CURRENT_VERSION_ID}+1"`

sudo dnf -y upgrade --refresh
sudo dnf -y install dnf-plugin-system-upgrade
sudo dnf -y system-upgrade download --refresh --releasever=${NEW_VERSION_ID}
sudo dnf -y system-upgrade reboot
